# # Name your project! Project names should contain only lowercase characters
# # and underscores. A good package name should reflect your organization's
# # name or the intended use of these models
# name: Final_project
# version: '1.0.0'
# config-version: 2

# # This setting configures which "profile" dbt uses for this project.
# profile: Final_project

# # These configurations specify where dbt should look for different types of files.
# # The `model-paths` config, for example, states that models in this project can be
# # found in the "models/" directory. You probably won't need to change these!
# model-paths: ["models"]
# analysis-paths: ["analyses"]
# test-paths: ["tests"]
# seed-paths: ["seeds"]
# macro-paths: ["macros"]
# snapshot-paths: ["snapshots"]

# clean-targets:         # directories to be removed by `dbt clean`
#   - "target"
#   - "dbt_packages"


# # Configuring models
# # Full documentation: https://docs.getdbt.com/docs/configuring-models

# # In this example config, we tell dbt to build all models in the example/
# # directory as views. These settings can be overridden in the individual model
# # files using the `{{ config(...) }}` macro.
# models:
#   final_project:  # Changed from "Final_project" to "final_project"
#     # Config indicated by + and applies to all files under models/example/
#     mart:
#       +materialized: table
#     staging:
#       +materialized: table




name: Final_project
version: '1.0.0'
config-version: 2

profile: Final_project

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  Final_project:
    database: JMAN_ASSESSMENT
    materialized: table
  mart:
    schema: mart
  staging:
    schema: staging
